/// Mõõdikute kaust
table Calculations
	lineageTag: beddccab-aa39-4ac8-bca8-df4650ad69e1

	measure Blank =
			
			BLANK ()
		formatString: 0
		displayFolder: #Other
		lineageTag: e443383f-fdbd-433e-b771-5fa8447ce31e

	measure 'Avg. Response Time (Working Day Hours)' =
			
			AVERAGE ( '# incident'[WorkingDayHours] )
		formatString: 0
		displayFolder: #Calculations
		lineageTag: 80e7f362-6d2b-4a33-990c-c2529b9c4f78

	measure Label_Days/Hours =
			
			VAR ResponseTime = [Avg. Response Time (Working Day Hours)]
			VAR Days =
			    INT ( DIVIDE ( ResponseTime, 24 ) )
			VAR Hours =
			    MOD ( INT ( ResponseTime ), 24 )
			RETURN
			    IF ( NOT ISBLANK ( ResponseTime ), Days & "d & " & Hours & "h", BLANK () )
		displayFolder: #Labels_Titles\Labels
		lineageTag: 5cfeed28-7e68-4e67-87e2-3349441cf73b

	measure 'Count of cases' =
			
			COUNTROWS ( '# incident' )
		formatString: #,0
		displayFolder: #Calculations
		lineageTag: 1ae72074-8ce8-41c5-99a6-691dc19bddea

	measure Label_Days/Hours/cases =
			
			INT ( [Avg. Response Time (Working Day Hours)] / 24 ) & "d/"
			    & MOD ( INT ( [Avg. Response Time (Working Day Hours)] ), 24 ) & "h "
			    & IF (
			        NOT ( ISBLANK ( [Count of cases] ) ),
			        "(" & [Count of cases] & " cases)",
			        BLANK ()
			    )
		displayFolder: #Labels_Titles\Labels
		lineageTag: 3fc438b4-5a5b-4cd9-81a1-87d229179775

	measure 'Count of cases YoY Change' =
			
			VAR CurrentYear = [Count of cases]
			VAR _PreviousYear =
			    CALCULATE ( [Count of cases], SAMEPERIODLASTYEAR ( 'Date'[Date] ) )
			RETURN
			    CurrentYear - _PreviousYear
		formatString: +# ##0;-# ##0;0
		displayFolder: #Calculations
		lineageTag: c28ce2cf-276b-4996-a47a-339e94f36d3e

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Title_Detail table' =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE", "Detail tabel",
			    "en-US", "Detail table",
			    "Detail table"
			)
		displayFolder: #Labels_Titles\Titles
		lineageTag: 6c8645ab-baed-437d-b680-4ee1d56579e8

	measure 'Last refresh' =
			
			FORMAT ( VALUES ( 'Last Refresh'[Date Last Refreshed] ), "dd.mm.yyyy hh:mm" )
		displayFolder: #Other
		lineageTag: 7d41d4af-91ec-4f83-823a-03543e3ec9b1

	measure 'Title_Avg. response time columnchart title' =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE", "Avg. esmareageerimise aeg päevades/tundides",
			    "en-US", "Avg. first response time in days/hours",
			    "Avg. first response time in days/hours"
			)
		displayFolder: #Labels_Titles\Titles
		lineageTag: 8d0a57df-8f60-42d4-8942-efad3942874b

	measure Title_Report =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE", "Esmareageerimine ServiceDesk'is",
			    "en-US", "First Response in ServiceDesk",
			    "First Response in ServiceDesk"
			)
		displayFolder: #Labels_Titles\Titles
		lineageTag: 2af5f629-f918-4139-8ab2-e35136289fc9

	measure 'Title_Clear all filters' =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE", "Taasta filtri valikud",
			    "en-US", "Clear all filters",
			    "Clear all filters"
			)
		displayFolder: #Labels_Titles\Titles
		lineageTag: 2a83f39b-88de-44d9-9f0e-2142e2a394a1

	measure 'Title_Avg. Response time card' =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE", "Avg. esmareageerimise aeg",
			    "en-US", "Avg. response time",
			    "Avg. response time"
			)
		displayFolder: #Labels_Titles\Titles
		lineageTag: db0b4dd0-2f3a-4e6c-9950-efc4ea2c3cf6

	measure 'Title_count of cases card' =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE", "Pöördumiste arv",
			    "en-US", "Count of cases",
			    "Count of cases"
			)
		displayFolder: #Labels_Titles\Titles
		lineageTag: 3be67cbe-9b53-4b2a-ab95-99c4d7bdbcc8

	measure Title_Infopanel =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE", "Ava infopaneel",
			    "en-US", "Open infopanel",
			    "Open infopanel"
			)
		displayFolder: #Labels_Titles\Titles
		lineageTag: 5c3ca20a-735b-4f4c-b6ba-3f81adfcfb5b

	measure Label_Info_text =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE",
			        "• Esmareageerimise aja arvutamisel on välja jäetud nädalavahetused ja riigipühad",
			    "en-US",
			        "• Weekends and public holidays are excluded from the first response time calculation",
			    "• Weekends and public holidays are excluded from the first response time calculation"
			)
		displayFolder: #Labels_Titles\Labels
		lineageTag: d5830546-6c09-4919-8929-54771c8ebfc6

	measure Subtitle_Table =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE", "Mitme tulba sortimiseks hoia all 'Shift'",
			    "en-US", "To sort multiple columns, hold down 'Shift'",
			    "To sort multiple columns, hold down 'Shift'"
			)
		displayFolder: #Labels_Titles\Titles
		lineageTag: 805cf5dc-58cb-4e97-86cd-1305ca971a30

	measure Target =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE", "2 tööpäeva",
			    "en-US", "2 workdays",
			    "2 workdays"
			)
		displayFolder: #Other
		lineageTag: 5436a1c4-9bb9-4214-9bd7-90dbc4ac3d27

	measure 'Avg.response time color' =
			
			IF ( [Avg. Response Time (Working Day Hours)] >= 48, "#FF6400", "#2E3844" )
		displayFolder: #Other
		lineageTag: 35f28f3c-3edb-41e0-8d8d-660a35816aae

	measure 'Only relevant values' =
			
			INT ( NOT ISEMPTY ( '# incident' ) )
		formatString: 0
		displayFolder: #Other
		lineageTag: bc352f32-8fe4-429d-895f-2d566f5a1a48

	measure 'Avg.response time color (Columns)' =
			
			IF ( [Avg. Response Time (Working Day Hours)] >= 48, "#B0B1B3", "#2E3844" )
		displayFolder: #Other
		lineageTag: a25c2d7b-de49-4601-bf1f-46a78c20187a

	measure Icon_Condition =
			
			MAXX (
			    '# incident',
			    IF (
			        ( '# incident'[statecodename] = "Active" )
			            && ISBLANK ( '# incident'[First Response Sent On] )
			            && [Avg. Response Time (Working Day Hours)] <= 48,
			        1,
			        IF ( [Avg. Response Time (Working Day Hours)] <= 48, 2, 3 )
			    )
			)
		formatString: 0
		displayFolder: #Other
		lineageTag: 8399e931-e6f0-4528-ba30-ce0a626afda9

	measure '% Response W.I 22 Working Days' =
			
			VAR TotalResponses =
			    COUNTROWS ( '# incident' )
			VAR ResponsesWithin2Days =
			    CALCULATE (
			        COUNTROWS ( '# incident' ),
			        '# incident'[Response in time] = "within 2 working days"
			    )
			RETURN
			    DIVIDE ( ResponsesWithin2Days, TotalResponses, 0 )
		formatString: 0%;-0%;0%
		displayFolder: #Calculations
		lineageTag: d913f7eb-e43d-41cc-884a-293893ed0b84

	measure Count_of_Cases_Description =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE", "Pöördumiste arv ServiceDesk'is valitud perioodil",
			    "en-US", "The count of cases in ServiceDesk during the selected period",
			    "The count of cases in ServiceDesk during the selected period"
			)
		displayFolder: #Labels_Titles\Labels
		lineageTag: 58aa5207-5b95-4de7-ac0f-ed5252652d48

	measure Target_Description =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE", "Seatud eesmärk juhtkonna poolt",
			    "en-US", "The goal set by the management",
			    "The goal set by the management"
			)
		displayFolder: #Labels_Titles\Labels
		lineageTag: f4955c82-bf42-4abd-b8bc-65793fabc38b

	measure 'AVG. Respone_Time_Description' =
			
			SWITCH (
			    USERCULTURE (),
			    "et-EE", "Keskmine esmareageerimise aeg ServiceDesk'i pöördumistele päevades/tundides",
			    "en-US", "Average first response time in days/hours for ServiceDesk cases",
			    "Average first response time in days/hours for ServiceDesk cases"
			)
		displayFolder: #Labels_Titles\Labels
		lineageTag: ed69ceab-6896-416d-a83f-4f352fe7a422

	measure 'filter icon' =
			
			"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAMAAADDpiTIAAAAAXNSR0IArs4c6QAA"
		displayFolder: #Other\Filter Display
		lineageTag: a425ba9f-4010-450b-9184-5c0f876d903e

	measure 'Number of Filters' =
			
			FORMAT (
			    IF ( ISFILTERED ( '# incident'[Case Type] ), 1 )
			        + IF ( ISFILTERED ( '# incident'[Warranty] ), 1 )
			        + IF ( ISFILTERED ( '≡ account'[Internal/External] ), 1 )
			        + IF ( ISFILTERED ( '≡ col_customerproduct'[Business Line Digital] ), 1 )
			        + IF ( ISFILTERED ( '# incident'[Response in time] ), 1 )
			        + IF ( ISFILTERED ( '≡ account'[Account Name] ), 1 )
			        + IF ( ISFILTERED ( '≡ account'[Owner] ), 1 )
			        + IF ( ISFILTERED ( '# incident'[statuscodename] ), 1 )
			        + IF ( ISFILTERED ( '# incident'[Sub Status] ), 1 ),
			    "#"
			)
		displayFolder: #Other\Filter Display
		lineageTag: 17b59698-ab73-4460-a8c6-8138fdcc926c

	measure 'Is filtered black' =
			
			IF ( [Number of Filters] = "", "#FFFFFF00", "#111111" )
		displayFolder: #Other\Filter Display
		lineageTag: 172b5299-1c1a-48b5-a024-59799b15a8b0

	measure 'Is filtered Green' =
			
			IF ( [Number of Filters] = "", "#FFFFFF00", "#C8FFCE" )
		displayFolder: #Other\Filter Display
		lineageTag: 3cd58c47-352e-44f0-abfd-b2ce4a1ea5ac

	partition Calculations = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

